export const RETIRED_WEBSITE_SLUGS = [
  'arunalu-biyagama',
  'capital-point-delgoda',
  'dreamland-dompe',
  'liberty-kaduwela',
  'new-life-kadawatha',
  'kingston-park-malabe',
  'guru-gedara-dompe',
  'free-zone-delgoda',
  'royal-meadows-ja-ela',
  'sunset-ridge-kalutara',
  'hillside-grove-kandy',
  'harbour-view-galle',
  'city-gate-colombo',
  'lake-park-kurunegala',
  'approval-ui-test',
  'aaaaaaaaaaaaaaaaaaa',
];

export const WEBSITE_PROJECTS = [
  {
    slug: 'balummahara',
    title: 'Balummahara',
    location: 'Balummahara, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    priceFrom: 1750000,
    status: 'For Sale',
    hotOffer: true,
    phase: 'Ongoing',
    price: 'Rs. 175,000.00/per perch up',
    landArea: '8–12 perch',
    excerpt: 'A Gampaha-belt project with finished asphalt roads, marked plots, and clear deeds ready for building.',
    mapQuery: 'Balummahara, Gampaha, Sri Lanka',
    overview:
      'Balummahara is a build-ready residential land project with paved internal roads, boundary walls, and open plots suited to first homes and investment builds.',
    description: [
      'Finished asphalt internal roads',
      'Marked residential plots with road frontage',
      'Clear deeds & approved plans',
      'Electricity available along the site',
      'Quiet Gampaha neighbourhood',
      'Reservation from Rs. 100,000',
      'Bank-loan friendly payment structure',
    ],
    showOnProjects: true,
  },
  {
    slug: 'field-breeze-divulapitiya',
    title: 'Field Breeze – Divulapitiya',
    location: 'Divulapitiya, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    priceFrom: 1800000,
    status: 'For Sale',
    hotOffer: true,
    phase: 'Ongoing',
    price: 'Starting from Rs. 1,800,000.00/Full Land',
    landArea: '10 perch',
    excerpt: 'Facing Colombo–Kurunegala Road, beside coconut groves, with clear deeds and bank-loan friendly terms.',
    mapQuery: 'Divulapitiya, Sri Lanka',
    overview:
      'A ready-to-build land project in Divulapitiya with road frontage, three-phase electricity, and an easy reservation path.',
    description: [
      'Near Divulapitiya town',
      'Facing Colombo – Kurunegala Road number 5',
      'Coconut-grove plots with road frontage',
      'Clear deeds & approved plans',
      'Three phase electricity',
      'Only Rs. 100,000 for reservation',
      'Pay 30% and settle the rest with a bank loan',
      'Pay 50% in advance for an easy payment plan',
      'Attractive discounts for outright payments',
    ],
    showOnProjects: true,
  },
  {
    slug: 'kirindivela-serenity-park',
    title: 'Kirindivela – Serenity Park',
    location: 'Kirindivela, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    priceFrom: 960000,
    status: 'For Sale',
    price: 'Rs. 120,000.00/per perch up',
    landArea: '8–15 perch',
    excerpt: 'A park-like Kirindivela development with paved internal roads, coconut-grove plots, and a quiet Gampaha setting.',
    mapQuery: 'Kirindivela, Gampaha, Sri Lanka',
    overview:
      'Serenity Park in Kirindivela offers build-ready residential lots among coconut palms, with finished access roads and a calm neighbourhood feel.',
    description: [
      'Quiet Kirindivela neighbourhood',
      'Paved internal roads through coconut groves',
      'Level plots ready for construction',
      'Clear deeds & approved plans',
      'Electricity and water access',
      'Flexible perch extents',
      'Bank-loan friendly payment structure',
    ],
    showOnProjects: true,
  },
  {
    slug: 'meerigama',
    title: 'Meerigama',
    location: 'Meerigama, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    priceFrom: 1200000,
    status: 'For Sale',
    price: 'Rs. 120,000.00/per perch up',
    landArea: '8–12 perch',
    excerpt: 'Plotted Meerigama lots with a finished access road, boundary markers, and a site office ready for walk-in visits.',
    mapQuery: 'Meerigama, Gampaha, Sri Lanka',
    overview:
      'Meerigama is an available Myland project with clearly marked plots, gravel internal roads, and an on-site office for guided visits.',
    description: [
      'Marked residential plots ready for sale',
      'Finished access road into the site',
      'On-site office for walk-in visits',
      'Clear deeds & approved plans',
      'Boundary posts and plot numbering in place',
      'Reservation from Rs. 100,000',
      'Bank-loan friendly documentation',
    ],
    showOnProjects: true,
  },
  {
    slug: 'dompe',
    title: 'Dompe',
    location: 'Dompe, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    status: 'Completed',
    phase: 'Completed',
    price: 'Completed development',
    landArea: 'Handed over',
    excerpt: 'A completed Dompe development with finished roads and plots already handed over to owners.',
    mapQuery: 'Dompe, Sri Lanka',
    overview:
      'Dompe is a sold-out Myland project — a finished residential site with internal roads, drainage, and a settled neighbourhood.',
    description: [
      'Internal roads completed',
      'Plots handed over to owners',
      'Clear deeds issued',
      'Quiet Dompe neighbourhood',
      'Green surroundings with town access',
    ],
    showOnProjects: true,
  },
  {
    slug: 'kiribathgoda',
    title: 'Kiribathgoda',
    location: 'Kiribathgoda, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    status: 'Completed',
    phase: 'Completed',
    price: 'Completed development',
    landArea: 'Handed over',
    excerpt: 'A handed-over Kiribathgoda project close to town, now a settled residential pocket.',
    mapQuery: 'Kiribathgoda, Gampaha, Sri Lanka',
    overview:
      'Kiribathgoda is a completed Myland development — sold out, with roads and plots already in the hands of owners.',
    description: [
      'Completed internal road network',
      'Plots handed over to owners',
      'Clear deeds issued',
      'Close to Kiribathgoda town',
      'Established neighbourhood',
    ],
    showOnProjects: true,
  },
];
