export const WEBSITE_PROJECTS = [
  {
    slug: 'field-breeze-divulapitiya',
    title: 'Field Breeze – Divulapitiya',
    location: 'Divulapitiya, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    priceFrom: 1800000,
    status: 'For Sale',
    hotOffer: true,
    phase: 'Ongoing',
    price: 'Starting from Rs. 1,800,000.00/Full Land',
    landArea: '10 perch',
    excerpt: 'Facing Colombo–Kurunegala Road, beside a paddy field, with clear deeds and bank-loan friendly terms.',
    mapQuery: 'Divulapitiya, Sri Lanka',
    overview:
      'A ready-to-build land project in Divulapitiya with road frontage, three-phase electricity, and an easy reservation path.',
    description: [
      'Near Divulapitiya town',
      'Facing Colombo – Kurunegala Road number 5',
      'Facing a paddy field',
      'Clear deeds & approved plans',
      'Three phase electricity',
      'Only Rs. 100,000 for reservation',
      'Pay 30% and settle the rest with a bank loan',
      'Pay 50% in advance for an easy payment plan',
      'Attractive discounts for outright payments',
    ],
    showOnProjects: true,
  },
  {
    slug: 'kirindivela-serenity-park',
    title: 'Kirindivela – Serenity Park',
    location: 'Kirindivela, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    priceFrom: 960000,
    status: 'For Sale',
    price: 'Rs. 120,000.00/per perch up',
    landArea: '8–15 perch',
    excerpt: 'A park-like Kirindivela development with paved internal roads, coconut-grove plots, and a quiet Gampaha setting.',
    mapQuery: 'Kirindivela, Gampaha, Sri Lanka',
    overview:
      'Serenity Park in Kirindivela offers build-ready residential lots among coconut palms, with finished access roads and a calm neighbourhood feel.',
    description: [
      'Quiet Kirindivela neighbourhood',
      'Paved internal roads through coconut groves',
      'Level plots ready for construction',
      'Clear deeds & approved plans',
      'Electricity and water access',
      'Flexible perch extents',
      'Bank-loan friendly payment structure',
    ],
    showOnProjects: true,
  },
  {
    slug: 'arunalu-biyagama',
    title: 'Arunalu – Biyagama',
    location: 'Biyagama, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    status: 'Sold',
    price: 'Rs. 150,000.00/per perch up',
    landArea: '10 perch',
    excerpt: 'A Biyagama development close to the industrial zone — currently marked sold.',
    mapQuery: 'Biyagama, Sri Lanka',
    overview: 'A compact land project in Biyagama, well placed for families working around the industrial corridor.',
    description: [
      'Close to Biyagama industrial zone',
      'Quiet residential setting',
      'Clear deeds & approved plans',
      'Internal roads completed',
      'Electricity available',
    ],
    showOnProjects: true,
  },
  {
    slug: 'capital-point-delgoda',
    title: 'Capital Point – Delgoda',
    location: 'Delgoda, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    priceFrom: 1400000,
    status: 'For Sale',
    hotOffer: true,
    price: 'Rs. 175,000.00/per perch up',
    landArea: '8–12 perch',
    excerpt: 'A Delgoda land project with town connectivity and an investor-friendly starting price.',
    mapQuery: 'Delgoda, Sri Lanka',
    overview: 'Capital Point offers build-ready plots in Delgoda with clear paperwork and easy reservation.',
    description: [
      'Close to Delgoda town',
      'Facing a developed internal road',
      'Clear deeds & approved plans',
      'Three-phase electricity',
      'Reservation from Rs. 100,000',
      'Bank loan assistance available',
    ],
    showOnProjects: true,
  },
  {
    slug: 'dreamland-dompe',
    title: 'Dreamland – Dompe',
    location: 'Dompe, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    priceFrom: 1350000,
    status: 'For Sale',
    price: 'Rs. 135,000.00/per perch up',
    landArea: '10 perch',
    excerpt: 'Peaceful Dompe plots with paddy views, clear deeds, and guided site visits.',
    mapQuery: 'Dompe, Sri Lanka',
    overview:
      'Dreamland is a calm residential land project in Dompe, designed for families who want space without leaving the Gampaha belt.',
    description: [
      'Quiet Dompe neighbourhood',
      'Open surroundings with green views',
      'Clear deeds & approved plans',
      'Electricity and water access',
      'Easy payment options',
    ],
    showOnProjects: true,
  },
  {
    slug: 'liberty-kaduwela',
    title: 'Liberty – Kaduwela',
    location: 'Kaduwela, Colombo',
    district: 'Colombo',
    listingType: 'Residential Lands',
    status: 'Completed',
    phase: 'Completed',
    price: 'Completed development',
    landArea: 'Handed over',
    excerpt: 'A completed Kaduwela development with roads, plots, and community already in place.',
    mapQuery: 'Kaduwela, Sri Lanka',
    overview: 'Liberty is a completed MyLand project in Kaduwela — a reference for how our sites look after handover.',
    description: [
      'Completed internal road network',
      'Plots handed over to owners',
      'Clear deeds issued',
      'Established neighbourhood',
      'Close to Kaduwela town',
    ],
    showOnProjects: true,
  },
  {
    slug: 'new-life-kadawatha',
    title: 'New Life – Kadawatha',
    location: 'Kadawatha, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    status: 'Completed',
    phase: 'Completed',
    price: 'Completed development',
    landArea: 'Handed over',
    excerpt: 'A finished Kadawatha project near the MyLand office, now a settled residential pocket.',
    mapQuery: 'Kadawatha, Sri Lanka',
    overview:
      'New Life sits in Kadawatha, close to our office on Kandy Road — a completed site with families already building.',
    description: [
      'Walking distance to Kandy Road',
      'Completed roads and drainage',
      'Clear deeds issued',
      'Close to schools and shops',
    ],
    showOnProjects: true,
  },
  {
    slug: 'kingston-park-malabe',
    title: 'Kingston Park – Malabe',
    location: 'Malabe, Colombo',
    district: 'Colombo',
    listingType: 'Residential Lands',
    status: 'Completed',
    phase: 'Completed',
    price: 'Completed development',
    landArea: 'Handed over',
    excerpt: 'A completed Malabe project close to universities, IT parks, and the New Kandy Road.',
    mapQuery: 'Malabe, Sri Lanka',
    overview: 'Kingston Park is a completed Malabe development in one of Colombo’s fastest-growing residential corridors.',
    description: [
      'Close to Malabe town and universities',
      'Completed internal roads',
      'Clear deeds issued',
      'Strong long-term location value',
    ],
    showOnProjects: true,
  },
  {
    slug: 'guru-gedara-dompe',
    title: 'Guru Gedara – Dompe',
    location: 'Dompe, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    status: 'Completed',
    phase: 'Completed',
    price: 'Completed development',
    landArea: 'Handed over',
    excerpt: 'A handed-over Dompe project with a settled community and finished site infrastructure.',
    mapQuery: 'Dompe, Sri Lanka',
    overview: 'Guru Gedara is a completed Dompe site, showing the finish quality MyLand delivers at handover.',
    description: [
      'Completed road and drain network',
      'Plots handed over',
      'Clear deeds issued',
      'Quiet residential setting',
    ],
    showOnProjects: true,
  },
  {
    slug: 'free-zone-delgoda',
    title: 'Free Zone – Delgoda',
    location: 'Delgoda, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    status: 'Completed',
    phase: 'Completed',
    price: 'Completed development',
    landArea: 'Handed over',
    excerpt: 'A completed Delgoda development near the free-trade corridor, now fully handed over.',
    mapQuery: 'Delgoda, Sri Lanka',
    overview:
      'Free Zone is a completed Delgoda project, chosen by buyers who wanted industrial-corridor access with a residential feel.',
    description: [
      'Close to the free-trade zone',
      'Completed internal roads',
      'Clear deeds issued',
      'Plots handed over to owners',
    ],
    showOnProjects: true,
  },
  {
    slug: 'royal-meadows-ja-ela',
    title: 'Royal Meadows – Ja-Ela',
    location: 'Ja-Ela, Gampaha',
    district: 'Gampaha',
    listingType: 'Residential Lands',
    priceFrom: 4200000,
    status: 'For Sale',
    hotOffer: true,
    price: 'Starting from Rs. 4,200,000.00/Full Land',
    landArea: '10 perch',
    excerpt: 'Build-ready Ja-Ela plots near the airport corridor, with clear deeds and flexible payment terms.',
    mapQuery: 'Ja-Ela, Sri Lanka',
    overview:
      'Royal Meadows sits in Ja-Ela with quick access to the airport road, shops, and schools — suited to first homes and investment builds.',
    description: [
      'Minutes from Ja-Ela town',
      'Airport-corridor access',
      'Clear deeds & approved plans',
      'Three-phase electricity',
      'Reservation from Rs. 100,000',
      'Bank-loan friendly terms',
    ],
    showOnProjects: false,
  },
  {
    slug: 'sunset-ridge-kalutara',
    title: 'Sunset Ridge – Kalutara',
    location: 'Kalutara South, Kalutara',
    district: 'Kalutara',
    listingType: 'Residential Lands',
    priceFrom: 6800000,
    status: 'For Sale',
    price: 'Rs. 6,800,000.00/Full Land',
    landArea: '12 perch',
    excerpt: 'Coastal-belt Kalutara plots with road frontage, utilities, and a calm residential setting.',
    mapQuery: 'Kalutara, Sri Lanka',
    overview:
      'Sunset Ridge is a Kalutara land project for buyers who want southern-coast access without giving up a quiet neighbourhood.',
    description: [
      'Close to Kalutara town',
      'Level plots ready for construction',
      'Clear deeds & approved plans',
      'Electricity and water access',
      'Easy reservation path',
    ],
    showOnProjects: false,
  },
  {
    slug: 'hillside-grove-kandy',
    title: 'Hillside Grove – Kandy',
    location: 'Kundasale, Kandy',
    district: 'Kandy',
    listingType: 'Residential Lands',
    priceFrom: 9500000,
    status: 'For Sale',
    hotOffer: true,
    price: 'Rs. 9,500,000.00/Full Land',
    landArea: '15 perch',
    excerpt: 'Hill-country Kundasale plots with cool air, town access, and MyLand paperwork standards.',
    mapQuery: 'Kundasale, Kandy, Sri Lanka',
    overview: 'Hillside Grove offers Kandy-belt plots for buyers who want elevation, privacy, and a clear title pack.',
    description: [
      'Kundasale neighbourhood',
      'Hill-country setting',
      'Clear deeds & approved plans',
      'Road access',
      'Reservation from Rs. 100,000',
    ],
    showOnProjects: false,
  },
  {
    slug: 'harbour-view-galle',
    title: 'Harbour View – Galle',
    location: 'Bope, Galle',
    district: 'Galle',
    listingType: 'Residential Lands',
    priceFrom: 18500000,
    status: 'For Sale',
    price: 'Starting from Rs. 18,500,000.00/Full Land',
    landArea: '12 perch',
    excerpt: 'Southern-province Galle plots with town access and a strong long-stay or holiday-home case.',
    mapQuery: 'Galle, Sri Lanka',
    overview: 'Harbour View is a Galle land project for buyers looking south — close to town, with MyLand deed standards.',
    description: [
      'Close to Galle town',
      'Southern Province access',
      'Clear deeds & approved plans',
      'Utility access',
      'Easy reservation path',
    ],
    showOnProjects: false,
  },
  {
    slug: 'city-gate-colombo',
    title: 'City Gate – Colombo',
    location: 'Malabe, Colombo',
    district: 'Colombo',
    listingType: 'Commercial Lands',
    priceFrom: 32000000,
    status: 'For Sale',
    price: 'Rs. 32,000,000.00/Full Land',
    landArea: '8 perch',
    excerpt: 'A rare Malabe commercial-frontage lot on the New Kandy Road corridor, ready for mixed-use development.',
    mapQuery: 'Malabe, Sri Lanka',
    overview:
      'City Gate is a compact commercial land lot in Malabe, suited to boutique offices, clinics, or mixed-use builds in a high-demand corridor.',
    description: [
      'New Kandy Road catchment',
      'Commercial-frontage potential',
      'Clear deeds & approved plans',
      'Close to universities and IT parks',
      'Bank-loan friendly documentation',
    ],
    showOnProjects: false,
  },
  {
    slug: 'lake-park-kurunegala',
    title: 'Lake Park – Kurunegala',
    location: 'Kurunegala Town, Kurunegala',
    district: 'Kurunegala',
    listingType: 'Residential Lands',
    priceFrom: 3100000,
    status: 'For Sale',
    price: 'Starting from Rs. 3,100,000.00/Full Land',
    landArea: '10 perch',
    excerpt: 'Affordable Kurunegala plots with town access, clear deeds, and an easy reservation path.',
    mapQuery: 'Kurunegala, Sri Lanka',
    overview:
      'Lake Park offers value-led plots in Kurunegala for families who want North-Western Province access with MyLand paperwork standards.',
    description: [
      'Close to Kurunegala town',
      'Level residential plots',
      'Clear deeds & approved plans',
      'Electricity available',
      'Reservation from Rs. 100,000',
    ],
    showOnProjects: false,
  },
];
